export declare const config: {
    port: number;
    gatewayWs: string;
    setfarmUrl: string;
    prometheusUrl: string;
    dataJson: string;
    jobsJson: string;
    avatarsDir: string;
    cliPath: string;
    clawtabsConfig: string;
    gatewayToken: string;
    projectsJson: string;
    wsOrigin: string;
    authToken: string;
};
export declare const PATHS: {
    readonly openclawDir: string;
    readonly agentsDir: string;
    readonly configFile: string;
    readonly setfarmDb: string;
    readonly setfarmDir: string;
    readonly projectsDir: string;
    readonly mobileDir: string;
    readonly workspaceDir: string;
    readonly setfarmRepoDir: string;
    readonly npmGlobalBin: string;
    readonly eventsJsonl: string;
    readonly portRegistry: string;
    readonly serveBin: string;
};
